# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.tddui
canonical: https://interop.esante.gouv.fr/ig/fhir/tddui # the last part of canonical and id must be the same
name: TransfertDonneesDUI
title: Médicosocial - Transfert de données DUI
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build

dependencies:
    hl7.fhir.fr.core: 1.1.0
    ans.fhir.fr.annuaire: 1.0.0-ballot-2

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Spécifications fonctionnelles
        cadre_orientations.md:
            title : Cadre juridique et orientations organisationnelles
        contexte_metier.md:
            title : Organisation du contexte métier
        processus.md:
            title : Définition des processus collaboratifs
        modelisation_contenu.md :
            title : Modélisation du contenu du DUI
    contenu_dossier.md :
        title: Contenu du dossier
    specifications_techniques.md:
        synthese_flux.md:
            title: Synthèse des flux
        st_flux1.md:
            title: Flux 1 - Ajout d'un document
        st_flux2.md:
            title: Flux 2 - Ajout d'un lot de documents
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages

    tests.md:
        title: Tests      
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Spécifications fonctionnelles : 
        Cadre juridique et orientations organisationnelles : cadre_orientations.html
        Organisation du contexte métier : contexte_metier.html
        Définition des processus collaboratifs : processus.html
        Modélisation du contenu du DUI : modelisation_contenu.html
    Contenu du dossier : contenu_dossier.html
    Description des flux:
        Synthèse des flux: synthese_flux.html
        Flux 1 - Ajout d'un document: st_flux1.html
        Flux 2 - Ajout d'un lot de documents: st_flux2.html
    Ressources de conformité: artifacts.html
    Tests:   tests.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Documentation sur les IG": new-tab https://interop.esante.gouv.fr/ig/documentation/
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
